### ISSUE TITLE
Not working after the update.

### ISSUE THREAD

**Issue by mdhz** [theapu/Zebpay-Unblock#1]
Hello,

It was working till the last update and now Zebpay has updated their code.
Hope you'll find the solution for this update.

New ver : 1.0.96

**Comment by theapu** [comment]
Updated module in xposed repository for newer version of Zebpay app. Tested OK on Resurrection Remix 7.1.2 on OnePlus One.

**Comment by mdhz** [comment]
Update released today v2.0

Please update the module.
